source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5.1'

gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'simple_form'

gem 'bootstrap-sass', '~> 3.3.6'

gem 'mysql2'

gem 'jbuilder', '~> 2.0'

gem 'filterrific'

gem "coffee-rails", '~> 4.2.1'

gem 'will_paginate', '~> 3.1.0'

gem 'will_paginate-bootstrap'

gem 'chardinjs-rails'

gem 'momentjs-rails', '>= 2.9.0'

gem 'bootstrap-datepicker-rails'

gem 'impressionist'

gem 'devise'

gem 'rolify'

gem 'cancancan'

group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'awesome_print'
end

